 name: Web API Deploy Pipeline
 on: 
  push:
    paths:
      - '.github/workflows/**'
      - 'cicd-section.api/**'

 env:
  AWS_REGION: ap-northeast-1
  WCS_CLUSTER:  my-app-cluster
  WCS_SERVICE:  my-app-api-service
  WCS_REPOSITORY: my-app-api
  WCS_TASK_DEFINITION_API: cicd-section/.aws/task-def-api.json 

 permissions:


 jobs:
 #Test/Build
  test-and-build:
    runs-on: ubuntu-latest
    default:
      run:
        working-directory: cicd-section/api
    steps:
      # Checkout code
      - uses: actions/checkout@v4

      - name: Run Tests and Build an Image
        run: docker image build -t temp_api_image:latest .
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ AWS-REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Login to Amazon ECR
        id: login-ECR
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Push the image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker image tag temp_api_image:latest $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
          docker image push $ECR_REGISTORY/$ECR_REPOSITRY:${{ github.sha }}
 #Deploy 
